name: Bazel build and test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: gcr.io/gapic-images/googleapis-bazel
    steps:
    - uses: actions/checkout@v2

    - name: Cache Bazel files
      id: cache-bazel
      uses: actions/cache@v2
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-bazel

    - name: Cache not found
      if: steps.cache-bazel.outputs.cache-hit != 'true'
      run: echo "No cache found."

    - name: Cache found
      if: steps.cache-bazel.outputs.cache-hit == 'true'
      run: |
        echo "Cache found. Cache size:"
        du -sh ~/.cache/bazel

    - name: Run bazel build in google/cloud/compute/v1
      run: bazel build '//google/cloud/compute/v1/...'

    - name: Run generated tests
      run: bazel test '//google/cloud/compute/v1/...'
