name: Bazel build and test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: gcr.io/gapic-images/googleapis-bazel:20210105
    # Dockerfile for this image is checked in on the top level of this repository
    steps:
    - uses: actions/checkout@v2

    - name: Cache Bazel files
      id: cache-bazel
      uses: actions/cache@v2
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-bazel-${{ jobs.build.container.image }}-${{ secrets.CACHE_VERSION }}

    - name: Cache not found
      if: steps.cache-bazel.outputs.cache-hit != 'true'
      run: |
        echo "No cache found. Cache key: ${{ runner.os }}-bazel-${{ jobs.build.container.image }}-${{ secrets.CACHE_VERSION }}"

    - name: Cache found
      if: steps.cache-bazel.outputs.cache-hit == 'true'
      run: |
        echo "Cache found. Cache key: ${{ runner.os }}-bazel-${{ jobs.build.container.image }}-${{ secrets.CACHE_VERSION }}"
        echo -n "Cache size: "
        du -sh ~/.cache/bazel
        echo "If the cache seems broken, update the CACHE_VERSION secret in"
        echo "https://github.com/googleapis/googleapis-discovery/settings/secrets/actions"
        echo "(use any random string, any GUID will work)"
        echo "and it will start over with a clean cache."
        echo "The old one will disappear after 7 days."

    - name: Run bazel build in google/cloud/compute/v1
      run: bazel build '//google/cloud/compute/v1/...'

    - name: Run generated tests
      run: bazel test '//google/cloud/compute/v1/...'
